#!/bin/bash


if [[ -d "${1}" ]];
then
  :
else
  printf "\nInput path ${1} not valid. Must be directory.\n"
  exit 1
fi


FILE_PATH="$(realpath "${1}")"

printf "import mediadapt.format_convert as fc ; fc.convert_all_webx('%s', webx_type='webp')", "$FILE_PATH" | python
