#!/bin/bash


FILE_PATH="$(realpath "${1}")"

echo "import mediadapt.format_convert as fc ; fc.open_img_source('${FILE_PATH}')" | python

# https://stackoverflow.com/questions/21934880/run-function-from-the-command-line-and-pass-arguments-to-function
# https://stackoverflow.com/questions/4139436/how-to-call-python-functions-when-running-from-terminal
